name: Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up node 
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'

    - run: npm ci
    
    - name: Update version in package.json
      run: npm --no-git-tag-version version ${{ github.event.release.tag_name }}

    - name: Commit changes to package.json
      uses: EndBug/add-and-commit@v5
      with:
        message: "Update version file for release: ${{ github.event.release.tag_name }}"
        add: "*.json"
        branch: main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish package
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
